import os
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'AI Hedge Fund Analysis Report', 0, 1, 'C')
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

# Create PDF
pdf = PDF()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)

# Add date
pdf.set_font('Arial', 'I', 10)
pdf.cell(0, 10, 'March 26, 2025', 0, 1, 'R')
pdf.ln(5)

# Executive Summary
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'Executive Summary', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'This report presents the analysis and trading recommendations generated by the AI Hedge Fund system for three major technology stocks: AAPL, MSFT, and NVDA. The analysis incorporates insights from multiple AI analysts, each with a unique investment philosophy and approach.')
pdf.ln(5)

# Portfolio Summary
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'Portfolio Summary', 0, 1, 'L')

# Table header
pdf.set_font('Arial', 'B', 10)
pdf.set_fill_color(240, 240, 240)
pdf.cell(40, 7, 'Ticker', 1, 0, 'C', True)
pdf.cell(40, 7, 'Action', 1, 0, 'C', True)
pdf.cell(40, 7, 'Quantity', 1, 0, 'C', True)
pdf.cell(40, 7, 'Confidence', 1, 1, 'C', True)

# Table data
pdf.set_font('Arial', '', 10)
# AAPL
pdf.cell(40, 7, 'AAPL', 1, 0, 'C')
pdf.set_text_color(231, 76, 60)  # Red for SHORT
pdf.cell(40, 7, 'SHORT', 1, 0, 'C')
pdf.set_text_color(0, 0, 0)  # Reset to black
pdf.cell(40, 7, '50', 1, 0, 'C')
pdf.cell(40, 7, '65.0%', 1, 1, 'C')
# MSFT
pdf.cell(40, 7, 'MSFT', 1, 0, 'C')
pdf.set_text_color(52, 152, 219)  # Blue for HOLD
pdf.cell(40, 7, 'HOLD', 1, 0, 'C')
pdf.set_text_color(0, 0, 0)  # Reset to black
pdf.cell(40, 7, '0', 1, 0, 'C')
pdf.cell(40, 7, '55.0%', 1, 1, 'C')
# NVDA
pdf.cell(40, 7, 'NVDA', 1, 0, 'C')
pdf.set_text_color(52, 152, 219)  # Blue for HOLD
pdf.cell(40, 7, 'HOLD', 1, 0, 'C')
pdf.set_text_color(0, 0, 0)  # Reset to black
pdf.cell(40, 7, '0', 1, 0, 'C')
pdf.cell(40, 7, '60.0%', 1, 1, 'C')
pdf.ln(5)

# Portfolio Strategy
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'Portfolio Strategy', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Multiple high-confidence bearish signals from valuation (76%), Cathie Wood (72%), Warren Buffett (75%), and sentiment (59%) suggest AAPL is overvalued. No strong bullish signals counter this perspective. Initiating a moderate short position to capitalize on potential downside while managing risk.')
pdf.ln(5)

# Detailed Analysis: NVDA
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'Detailed Analysis: NVDA', 0, 1, 'L')
pdf.set_font('Arial', 'B', 11)
pdf.cell(0, 7, 'Trading Decision', 0, 1, 'L')

# NVDA Analysis Table
pdf.set_font('Arial', 'B', 10)
pdf.set_fill_color(240, 240, 240)
pdf.cell(40, 7, 'Action', 1, 0, 'L', True)
pdf.set_font('Arial', '', 10)
pdf.set_text_color(52, 152, 219)  # Blue for HOLD
pdf.cell(120, 7, 'HOLD', 1, 1, 'L')
pdf.set_text_color(0, 0, 0)  # Reset to black

pdf.set_font('Arial', 'B', 10)
pdf.cell(40, 7, 'Quantity', 1, 0, 'L', True)
pdf.set_font('Arial', '', 10)
pdf.cell(120, 7, '0', 1, 1, 'L')

pdf.set_font('Arial', 'B', 10)
pdf.cell(40, 7, 'Confidence', 1, 0, 'L', True)
pdf.set_font('Arial', '', 10)
pdf.cell(120, 7, '60.0%', 1, 1, 'L')

pdf.set_font('Arial', 'B', 10)
pdf.cell(40, 7, 'Reasoning', 1, 0, 'L', True)
pdf.set_font('Arial', '', 10)
reasoning_text = 'Highly polarized signals with strong bullish views from Cathie Wood (85%), Phil Fisher (78%), and Druckenmiller (80%), countered by equally strong bearish signals from Bill Ackman (85%), Warren Buffett (85%), valuation (75%), and sentiment (72%). This extreme divergence indicates high volatility risk and suggests waiting for consensus to emerge.'
pdf.multi_cell(120, 7, reasoning_text, 1, 'L')
pdf.ln(5)

# AI Analysts
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'AI Analysts Contributing to This Analysis', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
analysts = [
    'Ben Graham', 'Bill Ackman', 'Cathie Wood', 'Charlie Munger',
    'Fundamentals Analyst', 'Phil Fisher', 'Sentiment Analyst',
    'Stanley Druckenmiller', 'Technical Analyst', 'Valuation Analyst',
    'Warren Buffett', 'Risk Management', 'Portfolio Management'
]

# Create a list of analysts
for analyst in analysts:
    pdf.cell(0, 7, '- ' + analyst, 0, 1, 'L')
pdf.ln(5)

# Methodology
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'Methodology', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'The AI Hedge Fund employs a multi-agent system where each agent analyzes the stocks from a different perspective. These analyses are then consolidated by the Risk Management and Portfolio Management agents to produce final trading decisions.')
pdf.ln(5)

# Disclaimer
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 10, 'Disclaimer', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.set_fill_color(255, 248, 225)
pdf.multi_cell(0, 5, 'This report is generated for educational purposes only and does not constitute financial advice. All trading decisions should be made in consultation with qualified financial advisors. Past performance is not indicative of future results.', 1, 'L', True)

# Save the PDF
pdf_path = 'ai_hedge_fund_report.pdf'
pdf.output(pdf_path)
print(f"PDF successfully created at: {os.path.abspath(pdf_path)}")
